<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Tooltip</name>
   <tag></tag>
   <elementGuidId>eeec0b06-2e2a-4aca-aad0-f4d70bbd3459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '491val-tooltip' and contains(@class, 'css-fqyi1o')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id, '3val-tooltip')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>491val-tooltip</value>
      <webElementGuid>3c602dbe-e375-45d1-a613-e075841747fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-fqyi1o</value>
      <webElementGuid>2cf34dbb-62ca-4198-ae5e-63e5f3e348c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
