<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Login</name>
   <tag></tag>
   <elementGuidId>0157e585-9631-4f78-b02d-812b938f4147</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fhs-btn-login']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class,'fhs-btn-login')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fhs-btn-login</value>
      <webElementGuid>5deea43d-551e-4a24-bd0f-3a59ed2ca29f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
